version: "3.8"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    restart: always

  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile.prod
    container_name: mern-frontend
    expose:
      - "3000"
    volumes:
      - ./my-app:/app
      - /app/node_modules
    env_file:
      - ./my-app/.env.production
    environment:
      - REACT_APP_BACKEND_URL=/api/
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: mern-backend
    expose:
      - "3005"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/config.prod.env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/MOE
      - HOST=http://${DOMAIN_NAME}/api
      - FRONTEND_URL=http://${DOMAIN_NAME}
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb-container
    volumes:
      - mongodb_data:/data/db
    restart: always
    # 生產環境中不應該直接暴露數據庫端口
    # ports:
    #   - "27017:27017"

volumes:
  mongodb_data:
    driver: local